name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Adjust to your PHP version

    - name: Install Composer Dependencies
      run: |
        composer update --no-ansi --prefer-dist --no-interaction --no-progress

    - name: Build PHP application
      run: |
        # Your build or application-specific commands go here

    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT  }}
